# Generated by Django 3.2.5 on 2022-01-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='category',
        ),
    ]
