# Generated by Django 3.2.5 on 2022-01-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auctions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categories',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
